### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by game-lover**
Directory for non-privileged user

### CODE REVIEW

**Comment by enty8080** [comment]
@game-lover What do you want?

**Comment by game-lover** [comment]
I want to add simple support for non-privileged user.

**Comment by enty8080** [comment]
@game-lover
When the first [U standart](https://ulang.netlify.app) will be released I’ll make all paths in `~/.u/stdlib`.

**Comment by game-lover** [comment]
You should use ~/.local/u or ~/.local/lib/u instead of ~/.u

**Comment by game-lover** [comment]
Why don't you want to merge pull request?

**Comment by enty8080** [comment]
@game-lover because when u10 will be released, your PR will be unusable.

**Comment by game-lover** [comment]
@enty8080 

Why? My pull request can be changed. But why do you want to set default folder to ~/.u/stdlib? Package can be not in stdlib.

**Comment by game-lover** [comment]
What does it mean "u10"?

**Comment by enty8080** [comment]
@game-lover there are three types of imports:

**1.** stdlib `~/.u/lib/u10`
`import studio`
**2.** custom `~/.u/lib`
`import "c/stdio`
**3.** local
`import "thisismymodule.u"`

If user defines `-std=<std>` or uses `pragma std <std>` then ulang compiler searches at `~/.u/lib/<std>`, if not, ulang searches at `~/.u/lib/u10` (current standart) or at `~/.u/lib`.

**Comment by game-lover** [comment]
@enty8080

Why ~/.u ?

**Comment by enty8080** [comment]
@game-lover this is just a logic

**Comment by game-lover** [comment]
@enty8080

> @game-lover this is just a logic 

Nope, it isn't logic

**Comment by enty8080** [comment]
@game-lover 

If you have any questions about U, you can write me on Twitter, my account is **enty8080**.

**Pull request closed without merging**
